In [2]:
%pip install nptyping beartype --upgrade --force  

Note: you may need to restart the kernel to use updated packages.
INFO: pip is looking at multiple versions of nptyping to determine which version is compatible with other requirements. This could take a while.
INFO: pip is still looking at multiple versions of nptyping to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
                  ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\http\client.py", line 479, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell1\anaconda3\envs\python12\L

In [3]:
# isntall nptyping beartype and if these packages installed then upgradge forec fully 

In [4]:
%pip install nptyping beartype

  Using cached nptyping-2.5.0-py3-none-any.whl.metadata (7.6 kB)
  Using cached beartype-0.18.5-py3-none-any.whl.metadata (30 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     -

ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
                  ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\http\client.py", line 479, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell1\anaconda3\envs\python12\L


     -------------------- ------------------- 30.7/61.0 kB 2.0 kB/s eta 0:00:16
     -------------------- ------------------- 30.7/61.0 kB 2.0 kB/s eta 0:00:16
     -------------------- ------------------- 30.7/61.0 kB 2.0 kB/s eta 0:00:16
     -------------------- ------------------- 30.7/61.0 kB 2.0 kB/s eta 0:00:16
     -------------------- ------------------- 30.7/61.0 kB 2.0 kB/s eta 0:00:16
     -------------------- ------------------- 30.7/61.0 kB 2.0 kB/s eta 0:00:16
     -------------------- ------------------- 30.7/61.0 kB 2.0 kB/s eta 0:00:16
     -------------------- ------------------- 30.7/61.0 kB 2.0 kB/s eta 0:00:16
     -------------------- ------------------- 30.7/61.0 kB 2.0 kB/s eta 0:00:16
     -------------------- ------------------- 30.7/61.0 kB 2.0 kB/s eta 0:00:16
     -------------------- ------------------- 30.7/61.0 kB 2.0 kB/s eta 0:00:16
     -------------------- ------------------- 30.7/61.0 kB 2.0 kB/s eta 0:00:16
     -------------------- -------------

In [5]:
%pip install nptyping beartype --upgrade --force  


  Using cached nptyping-2.5.0-py3-none-any.whl.metadata (7.6 kB)
  Using cached beartype-0.18.5-py3-none-any.whl.metadata (30 kB)
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Using cached nptyping-2.5.0-py3-none-any.whl (37 kB)
   ---------------------------------------- 0.0/917.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/917.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/917.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/917.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/917.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/917.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/917.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/917.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/917.8 kB ? eta -:--:--
   ---------------------------------------- 0.0/917.8 kB ? eta -:--:--
   --------------------------------

ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
                  ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell1\anaconda3\envs\python12\Lib\http\client.py", line 479, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell1\anaconda3\envs\python12\L

   -------- ------------------------------ 204.8/917.8 kB 24.0 kB/s eta 0:00:30
   -------- ------------------------------ 204.8/917.8 kB 24.0 kB/s eta 0:00:30
   -------- ------------------------------ 204.8/917.8 kB 24.0 kB/s eta 0:00:30
   -------- ------------------------------ 204.8/917.8 kB 24.0 kB/s eta 0:00:30
   -------- ------------------------------ 204.8/917.8 kB 24.0 kB/s eta 0:00:30
   -------- ------------------------------ 204.8/917.8 kB 24.0 kB/s eta 0:00:30
   -------- ------------------------------ 204.8/917.8 kB 24.0 kB/s eta 0:00:30
   -------- ------------------------------ 204.8/917.8 kB 24.0 kB/s eta 0:00:30
   -------- ------------------------------ 204.8/917.8 kB 24.0 kB/s eta 0:00:30
   -------- ------------------------------ 204.8/917.8 kB 24.0 kB/s eta 0:00:30
   -------- ------------------------------ 204.8/917.8 kB 24.0 kB/s eta 0:00:30
   -------- ------------------------------ 204.8/917.8 kB 24.0 kB/s eta 0:00:30
   -------- ----------------------------

## Scalar value 

In [1]:
import numpy as np 

a : np.ndarray = np.array(1000) # object to store

display(a) # prints
display(a.shape) # prints the shape of the object () = 0 shape is round bracket open and close 
display(a.dtype) # prints the dtype of the object
display(type(a)) 
display(a.ndim) # prints the number of dimensions. Scalar value dimension always zero
display(a.size) # prints the size of the object meaning its no of items
display(a.itemsize) # prints the itemsize of the object

# these are basic properties of the object

array(1000)

()

dtype('int64')

numpy.ndarray

0

1

8

In [2]:
import numpy as np

a : np.ndarray = np.array([1,2,3,4]) # object to store [1,2,3,4] = called vector

display(f" object {a}") # prints
display(f"objec shape {a.shape}") # prints the shape of the object () = 4, numpy ne default ye show karwya ke no of items show ho rhe 
display(f" Object type {a.dtype}") # prints the dtype of the object
display(f"Object type with global function {type(a)}") # prints the dtype of the
display(f"Number of dimension {a.ndim}") # prints the number of dimensions. Vector dimension will be 1 
display(f"Total items in Array : {a.size}") # prints the size of the object
display(f"{a.itemsize}") # prints the itemsize of the object

' object [1 2 3 4]'

'objec shape (4,)'

' Object type int64'

"Object type with global function <class 'numpy.ndarray'>"

'Number of dimension 1'

'Total items in Array : 4'

'8'

## Matrix dimensions

In [4]:
import numpy as np

data = [[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]]

a : np.ndarray = np.array(data) # object to store = Matrix meaning it's 2 dimensions buz it has 2 square brackets after = 

display(f" object {a}") # prints
display(f"objec shape {a.shape}") # prints the shape of the object () = meaning it has 3 rows and 4 columns.
display(f" Object type {a.dtype}") # prints the dtype of the object
display(f"Object type with global function {type(a)}") # prints the dtype of the
display(f"Number of dimension {a.ndim}") # prints the number of dimensions
display(f"Total items in Array : {a.size}") # prints the size of the object
display(f"{a.itemsize}") # prints the itemsize of the object

' object [[ 0  1  2  3]\n [ 4  5  6  7]\n [ 8  9 10 11]]'

'objec shape (3, 4)'

' Object type int64'

"Object type with global function <class 'numpy.ndarray'>"

'Number of dimension 2'

'Total items in Array : 12'

'8'

## Numpy with NDArray typing support

In [2]:
%pip install nptyping

Note: you may need to restart the kernel to use updated packages.


In [12]:
%pip install nptyping beartype --upgrade --force  


  Using cached nptyping-2.5.0-py3-none-any.whl.metadata (7.6 kB)
  Using cached beartype-0.18.5-py3-none-any.whl.metadata (30 kB)
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Using cached nptyping-2.5.0-py3-none-any.whl (37 kB)
Using cached beartype-0.18.5-py3-none-any.whl (917 kB)
Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: beartype
    Found existing installation: beartype 0.18.5
    Uninstalling beartype-0.18.5:
      Successfully uninstalled beartype-0.18.5
  Attempting uninstall: nptyping
    Found existing installation: nptyping 2.5.0
    Uninstalling nptyping-2.5.0:
      Successfully uninstalled nptyping-2.5.0
Note: you may need to restart the kernel to use updated packages.


  You can safely remove it manually.
  You can safely remove it manually.


In [3]:
from nptyping import NDArray, Shape, UInt64
from typing import Any
import numpy as np  # Ensure numpy is imported

#              shape list 10 tak ke list banaou and it's type is any
data: NDArray[Shape["10"], Any] = np.arange(1, 11)

print(data)   # it's one dimententional array
print(data + 5)  # Addition operation


[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]


In [4]:
d1 : list[int] = [1,2,3,4,5,6,7,8,9,10]
d1 + 5  # in list we can't perform the addition but in numpy we can perform

TypeError: can only concatenate list (not "int") to list

In [6]:
d1 : list[int] = [1,2,3,4,5,6,7,8,9,10]
[i+5 for i in d1 ]

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [7]:
%%time  # it shows time 
# when we add 5 over 10000 through numpy 
data : NDArray[Shape["10"], Any] = np.arange(1,10000000)

data + 5 # addition operation 

CPU times: total: 31.2 ms
Wall time: 32.6 ms


array([       6,        7,        8, ..., 10000002, 10000003, 10000004])

In [10]:
%%time
# when we add 5 over 10000 through list 
data : list[int] = list(range(1,1000))

[i + 5  for i in data]# addition operation


CPU times: total: 15.6 ms
Wall time: 3.24 ms


[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


## numpy advanced operations vs list operations

In [12]:
data : list[int] = list(range(1,21))
print(data)
print(data[5:11])  # slicing normal python

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


In [14]:
data : list[int] = list(range(1,21))
print(data)
print(data[5:11])
data[5:11] = 10 # normal python list we can't assign value 
print(data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


TypeError: can only assign an iterable

In [15]:
ndata : NDArray[Shape["20"], Any] = np.arange(1,21)
print(ndata)
print(ndata[5:11]) # slicing 
ndata[5:11] = 1000 # after slicing i want to update data from to 11
print(ndata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


## Numpy 1d functions

In [16]:
state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])  # np.array convert tuple list or anything into array
#                         100 numbers generate kro  np.random meanning random number generate kro 1 se le kr 100 tak link 1 se 100 ke darmian 20 randomn number generate kro 
ubl_bank : NDArray[Shape["100"],Any] = np.random.randint(1,100, 20)

display(state_bank)
display(ubl_bank)

array([ 1,  7,  8, 10])

array([15, 19,  5, 27, 50, 78, 34, 52, 41, 55, 41, 57, 51, 76, 57, 51,  8,
       74, 35,  2])

In [31]:
from nptyping import Bool

state_bank : NDArray[Shape["4"],Any] = np.array([1,7,8,10])
#[1,      7,      8,     10]
#[True,  False, False, True]
#variable[[True,  False, False, True]]
#[1,10]
select : NDArray[Shape["4"],Bool]= np.array([True, False, True, False])

state_bank[select] # it will show true 

array([1, 8])

In [33]:
state_bank : NDArray[Shape["4"],Any] = np.array([1,7,8,10])
state_bank [state_bank % 2 == 0]   # jaha jaha true hoga it will show true

array([ 8, 10])

In [35]:
state_bank : NDArray[Shape["4"],Any] = np.array([1,7,8,10])
state_bank % 2 == 0

array([False, False,  True,  True])

In [36]:
display(state_bank)
display(ubl_bank)

#        4item       search from 20 items  np.in1d meaning 1 dimensioansl 
np.in1d(state_bank, ubl_bank) # first variable items length returned  # mtlb sirf 8 hamare kaam ka hai 

array([ 1,  7,  8, 10])

array([15, 19,  5, 27, 50, 78, 34, 52, 41, 55, 41, 57, 51, 76, 57, 51,  8,
       74, 35,  2])

array([False, False,  True, False])

In [37]:
display(state_bank)
display(ubl_bank)

#        4item       search 20 items
state_bank[np.in1d(state_bank,ubl_bank)] # first variable items length returned. Issne hare 8 nikal kr de dia 

array([ 1,  7,  8, 10])

array([15, 19,  5, 27, 50, 78, 34, 52, 41, 55, 41, 57, 51, 76, 57, 51,  8,
       74, 35,  2])

array([8])

In [38]:
np.intersect1d(state_bank,ubl_bank)

array([8])

In [ ]:
x : NDArray[Shape["5"],Any] = np.array([1,3,4,5,7]) # dimensiona
y : NDArray[Shape["5"],Any] = np.array([6,3,2,5,100]) # dimensiona

display(x)
display(y)
np.where(x > y, x, y) # comparison between dimensions

## Create Numpy arrays

In [39]:
a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2, 3], # size, size meaning two dimensions with any data type 
                                                      [4, 5, 6]])
print(a)

a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2],
                                                      [4, 5]])
print(a)

a : NDArray[Shape["Size, Size"], Any] = np.array([["A"],
                                                    ["B"]])
print(a) # create two dimensions for each with any data type 

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [40]:
a : NDArray[Shape["*, *"], Any] = np.array([[1, 2, 3], # staic or size both have the same shape 
                                                      [4, 5, 6]])
print(a)

a : NDArray[Shape["*, *"], Any] = np.array([[1, 2],
                                                      [4, 5]])
print(a)

a : NDArray[Shape["*, *"], Any] = np.array([["A"],
                                                    ["B"]])

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [41]:
np.who()

Name            Shape            Bytes            Type

_               1                4                int32
__              1                4                int32
___             4                4                bool
data            10               40               int32
_7              9999999          39999996         int32
ndata           20               80               int32
state_bank      4                16               int32
ubl_bank        20               80               int32
select          4                4                bool
_17             2                8                int32
_18             2                8                int32
_19             2                8                int32
_20             2                8                int32
_21             2                8                int32
_22             2                8                int32
_23             2                8                int32
_25             2                8                

## Create any dimension array

In [42]:
a : NDArray[Shape["Size"],Any] = np.arange(1,5)
print(a)
a : NDArray[Shape["Size"],Any] = np.arange(1,10)
print(a)

[1 2 3 4]
[1 2 3 4 5 6 7 8 9]


In [45]:
a : NDArray[Shape["Size, Size"],Any] = np.arange(3*3).reshape(3,3) #show me 3 rows and 3 columns
print(a)
a : NDArray[Shape["Size, Size"],Any] = np.arange(5*3).reshape(5,3) # 5 rows and 3 columns.
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [47]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(2*3*3).reshape(2,3,3) # 2 means 3 copyies 3 rows 3 columns   
print(a)
print('=======')
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [50]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[::2,::,::] # slicing 

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]]])

In [51]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[a%2==0] # modulus woh numbers jo 2 pr divide hote hun 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
np.asarray([1,2,3]) # asarray used for conversion into array 


array([1, 2, 3])

In [54]:
np.zeros(10) # generate zeros 10 times. 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.zeros((2,2)) # 2 rows 2 columns by fill with zeros 

array([[0., 0.],
       [0., 0.]])

In [56]:
np.ones((2,2)) # fill with ones     

array([[1., 1.],
       [1., 1.]])

In [59]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [60]:
np.ones_like(a) # fill with ones 

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [62]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[[0,-1],::,::] # 0 zero means first list and -1 means last list pick kro :: :: suntax hai just 

array([[[ 0,  1],
        [ 2,  3]],

       [[16, 17],
        [18, 19]]])

In [65]:
ndata : NDArray[Shape["20"], Any] = np.arange(1,21)

print(ndata)
print(ndata.min())
print(ndata.max())
print(ndata.argmax()) # it shows index value of max value 
print(ndata.argmin()) # it shows index value of min value 
print(ndata.mean()) # it find mean 
print(ndata.std()) # it find standard deviation
print(ndata.sum()) # it find sum
print(ndata.cumsum()) # it find cumsum

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
20
19
0
10.5
5.766281297335398
210
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
